version: '3.9'

services:
  # Backend - Express app
  backend:
    build:
      context: ./backend  # Directorio donde está el código de tu backend (Express)
      dockerfile: Dockerfile  # Asegúrate de tener un Dockerfile para el backend
    image: express-app
    ports:
      - "3000:3000"  # Exponer el puerto del backend (puedes cambiarlo si es necesario)
    volumes:
      - ./backend:/usr/src/app  # Enlazar el código del backend a la aplicación dentro del contenedor
    environment:
      - POSTGRES_PASSWORD=densityLabs
    depends_on:
      - db  # Asegurarse de que la base de datos esté lista antes de iniciar el backend

  # Frontend - React app
  frontend:
    build:
      context: ./frontend  # Directorio donde está el código de tu frontend (React)
      dockerfile: Dockerfile  # Asegúrate de tener un Dockerfile para el frontend
    image: react-app
    ports:
      - "3001:3001"  # Exponer el puerto del frontend
    volumes:
      - ./frontend:/usr/src/app  # Enlazar el código del frontend al contenedor
    environment:
      - CHOKIDAR_USEPOLLING=true  # Asegurarse de que React funcione bien en Docker
    depends_on:
      - backend  # Esperar que el backend esté listo antes de iniciar el frontend

  # Database - PostgreSQL
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: densityLabs
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
